// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.1
// source: proto/demo/v1/demo.proto

package demov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_demo_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	PodIp         string                 `protobuf:"bytes,3,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_demo_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *EchoResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *EchoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_demo_v1_demo_proto protoreflect.FileDescriptor

const file_proto_demo_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x18proto/demo/v1/demo.proto\x12\ademo.v1\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"k\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x15\n" +
	"\x06pod_ip\x18\x03 \x01(\tR\x05podIp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion2B\n" +
	"\vDemoService\x123\n" +
	"\x04Echo\x12\x14.demo.v1.EchoRequest\x1a\x15.demo.v1.EchoResponseB\x1eZ\x1cdemoapp/proto/demo/v1;demov1b\x06proto3"

var (
	file_proto_demo_v1_demo_proto_rawDescOnce sync.Once
	file_proto_demo_v1_demo_proto_rawDescData []byte
)

func file_proto_demo_v1_demo_proto_rawDescGZIP() []byte {
	file_proto_demo_v1_demo_proto_rawDescOnce.Do(func() {
		file_proto_demo_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_demo_v1_demo_proto_rawDesc), len(file_proto_demo_v1_demo_proto_rawDesc)))
	})
	return file_proto_demo_v1_demo_proto_rawDescData
}

var file_proto_demo_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_demo_v1_demo_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: demo.v1.EchoRequest
	(*EchoResponse)(nil), // 1: demo.v1.EchoResponse
}
var file_proto_demo_v1_demo_proto_depIdxs = []int32{
	0, // 0: demo.v1.DemoService.Echo:input_type -> demo.v1.EchoRequest
	1, // 1: demo.v1.DemoService.Echo:output_type -> demo.v1.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_demo_v1_demo_proto_init() }
func file_proto_demo_v1_demo_proto_init() {
	if File_proto_demo_v1_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_demo_v1_demo_proto_rawDesc), len(file_proto_demo_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demo_v1_demo_proto_goTypes,
		DependencyIndexes: file_proto_demo_v1_demo_proto_depIdxs,
		MessageInfos:      file_proto_demo_v1_demo_proto_msgTypes,
	}.Build()
	File_proto_demo_v1_demo_proto = out.File
	file_proto_demo_v1_demo_proto_goTypes = nil
	file_proto_demo_v1_demo_proto_depIdxs = nil
}
